import { InventoryDto } from "../types/inventory/inventoryDto";
import { TransactionDto } from "../types/transaction/TransactionDto";

export const inventoryData: InventoryDto[] = [
    {
      inventoryId: 1,
      product: 'Laptop',
      code: 'LP123',
      category: 'Electronics',
      unit: 'pcs',
      stock: 30,
      lastTransaction: new Date('2025-02-01'),
    },
    {
      inventoryId: 2,
      product: 'Smartphone',
      code: 'SP456',
      category: 'Electronics',
      unit: 'pcs',
      stock: 50,
      lastTransaction: new Date('2025-01-20'),
    },
    {
      inventoryId: 3,
      product: 'Headphones',
      code: 'HP789',
      category: 'Accessories',
      unit: 'pcs',
      stock: 150,
      lastTransaction: new Date('2025-01-28'),
    },
    {
      inventoryId: 4,
      product: 'Keyboard',
      code: 'KB101',
      category: 'Accessories',
      unit: 'pcs',
      stock: 75,
      lastTransaction: new Date('2025-01-15'),
    },
    {
      inventoryId: 5,
      product: 'Mouse',
      code: 'MS202',
      category: 'Accessories',
      unit: 'pcs',
      stock: 120,
      lastTransaction: new Date('2025-01-30'),
    },
    {
      inventoryId: 6,
      product: 'Monitor',
      code: 'MN303',
      category: 'Electronics',
      unit: 'pcs',
      stock: 40,
      lastTransaction: new Date('2025-02-05'),
    },
    {
      inventoryId: 7,
      product: 'Tablet',
      code: 'TB404',
      category: 'Electronics',
      unit: 'pcs',
      stock: 60,
      lastTransaction: new Date('2025-01-10'),
    },
    {
      inventoryId: 8,
      product: 'Charger',
      code: 'CH505',
      category: 'Accessories',
      unit: 'pcs',
      stock: 200,
      lastTransaction: new Date('2025-01-22'),
    },
    {
      inventoryId: 9,
      product: 'Camera',
      code: 'CM606',
      category: 'Electronics',
      unit: 'pcs',
      stock: 25,
      lastTransaction: new Date('2025-01-18'),
    },
    {
      inventoryId: 10,
      product: 'Smartwatch',
      code: 'SW707',
      category: 'Accessories',
      unit: 'pcs',
      stock: 90,
      lastTransaction: new Date('2025-01-25'),
    },
    {
      inventoryId: 11,
      product: 'Laptop Bag',
      code: 'LB808',
      category: 'Accessories',
      unit: 'pcs',
      stock: 50,
      lastTransaction: new Date('2025-01-30'),
    },
    {
      inventoryId: 12,
      product: 'Speaker',
      code: 'SP909',
      category: 'Electronics',
      unit: 'pcs',
      stock: 80,
      lastTransaction: new Date('2025-01-12'),
    },
    {
      inventoryId: 13,
      product: 'External Hard Drive',
      code: 'EH1010',
      category: 'Electronics',
      unit: 'pcs',
      stock: 30,
      lastTransaction: new Date('2025-01-05'),
    },
    {
      inventoryId: 14,
      product: 'USB Cable',
      code: 'UC1111',
      category: 'Accessories',
      unit: 'pcs',
      stock: 500,
      lastTransaction: new Date('2025-01-29'),
    },
    {
      inventoryId: 15,
      product: 'Power Bank',
      code: 'PB1212',
      category: 'Accessories',
      unit: 'pcs',
      stock: 100,
      lastTransaction: new Date('2025-01-19'),
    }
  ];
  

  function generateRandomDate(startDate: Date, endDate: Date): Date {
    const randomTime = startDate.getTime() + Math.random() * (endDate.getTime() - startDate.getTime());
    return new Date(randomTime);  // Retorna un objeto Date
  }
  
  export const transactionsData: TransactionDto[] = [
    { transactionId: 1, movementType: 'Sale', transactionType: 'Credit', docNumber: 'INV001', quantity: 5, cost: 200, user: 'Alice', product: 'Laptop', entryDate: generateRandomDate(new Date(2023, 0, 1), new Date(2025, 0, 1)) },
    { transactionId: 2, movementType: 'Purchase', transactionType: 'Debit', docNumber: 'PO002', quantity: 10, cost: 50, user: 'Bob', product: 'Mouse', entryDate: generateRandomDate(new Date(2023, 0, 1), new Date(2025, 0, 1)) },
    { transactionId: 3, movementType: 'Sale', transactionType: 'Debit', docNumber: 'INV003', quantity: 3, cost: 150, user: 'Charlie', product: 'Keyboard', entryDate: generateRandomDate(new Date(2023, 0, 1), new Date(2025, 0, 1)) },
    { transactionId: 4, movementType: 'Purchase', transactionType: 'Credit', docNumber: 'PO004', quantity: 8, cost: 100, user: 'David', product: 'Monitor', entryDate: generateRandomDate(new Date(2023, 0, 1), new Date(2025, 0, 1)) },
    { transactionId: 5, movementType: 'Sale', transactionType: 'Credit', docNumber: 'INV005', quantity: 2, cost: 300, user: 'Eva', product: 'Printer', entryDate: generateRandomDate(new Date(2023, 0, 1), new Date(2025, 0, 1)) },
    { transactionId: 6, movementType: 'Purchase', transactionType: 'Debit', docNumber: 'PO006', quantity: 5, cost: 120, user: 'Frank', product: 'Tablet', entryDate: generateRandomDate(new Date(2023, 0, 1), new Date(2025, 0, 1)) },
    { transactionId: 7, movementType: 'Sale', transactionType: 'Debit', docNumber: 'INV007', quantity: 4, cost: 80, user: 'Grace', product: 'Smartphone', entryDate: generateRandomDate(new Date(2023, 0, 1), new Date(2025, 0, 1)) },
    { transactionId: 8, movementType: 'Purchase', transactionType: 'Credit', docNumber: 'PO008', quantity: 12, cost: 60, user: 'Henry', product: 'Headphones', entryDate: generateRandomDate(new Date(2023, 0, 1), new Date(2025, 0, 1)) },
    { transactionId: 9, movementType: 'Sale', transactionType: 'Credit', docNumber: 'INV009', quantity: 6, cost: 250, user: 'Ivy', product: 'Camera', entryDate: generateRandomDate(new Date(2023, 0, 1), new Date(2025, 0, 1)) },
    { transactionId: 10, movementType: 'Purchase', transactionType: 'Debit', docNumber: 'PO010', quantity: 7, cost: 130, user: 'Jack', product: 'Speaker', entryDate: generateRandomDate(new Date(2023, 0, 1), new Date(2025, 0, 1)) },
    { transactionId: 11, movementType: 'Sale', transactionType: 'Credit', docNumber: 'INV011', quantity: 1, cost: 500, user: 'Kathy', product: 'TV', entryDate: generateRandomDate(new Date(2023, 0, 1), new Date(2025, 0, 1)) },
    { transactionId: 12, movementType: 'Purchase', transactionType: 'Debit', docNumber: 'PO012', quantity: 9, cost: 40, user: 'Louis', product: 'Charger', entryDate: generateRandomDate(new Date(2023, 0, 1), new Date(2025, 0, 1)) },
    { transactionId: 13, movementType: 'Sale', transactionType: 'Debit', docNumber: 'INV013', quantity: 3, cost: 90, user: 'Mia', product: 'Bluetooth Speaker', entryDate: generateRandomDate(new Date(2023, 0, 1), new Date(2025, 0, 1)) },
    { transactionId: 14, movementType: 'Purchase', transactionType: 'Credit', docNumber: 'PO014', quantity: 4, cost: 160, user: 'Nina', product: 'Smartwatch', entryDate: generateRandomDate(new Date(2023, 0, 1), new Date(2025, 0, 1)) },
    { transactionId: 15, movementType: 'Sale', transactionType: 'Debit', docNumber: 'INV015', quantity: 2, cost: 400, user: 'Oscar', product: 'Drone', entryDate: generateRandomDate(new Date(2023, 0, 1), new Date(2025, 0, 1)) }
  ];